# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ece5db22f9aed674e68c0354c5c210b6df28628b7d3938b4de9b199ca95069523f8ecccd8f08bce6c0ff5d9c363156eb74b756a45250d4422147b20a8fb5e0c

test:
  secret_key_base: 852934d60c8ea95016c00c3528a93ff7a54fbf3ce4ff3dc483683e3e1333b8168865ae93b53e737c0347ad7a6368fcc2f5f40bc232df47fca9eb601cb7281939

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
